version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"
    hostname: client

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - "8000:8000"
    hostname: server
  
  socket:
    build:
      context: ./socket
      dockerfile: ./Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - "9000:9000"
    hostname: socket

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    
networks:
  default:
    driver: bridge
    name: zapzap2
